// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYSqe4buWmmknIlEDeTpPn_5cTYemdI8E',
    appId: '1:752415718905:web:74871a8f2c9b9330c8d128',
    messagingSenderId: '752415718905',
    projectId: 'agent-app-67bc4',
    authDomain: 'agent-app-67bc4.firebaseapp.com',
    storageBucket: 'agent-app-67bc4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXiBwYpGUc-__ebJ4VYkPEH-G0k-MxTV4',
    appId: '1:752415718905:android:ca63f4d482e650e2c8d128',
    messagingSenderId: '752415718905',
    projectId: 'agent-app-67bc4',
    storageBucket: 'agent-app-67bc4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjeQ5mDNzB6GvZlmdM1XWo3Wo1sIE5KGE',
    appId: '1:752415718905:ios:71c7e28df8799251c8d128',
    messagingSenderId: '752415718905',
    projectId: 'agent-app-67bc4',
    storageBucket: 'agent-app-67bc4.firebasestorage.app',
    iosClientId: '752415718905-46n420cu1l4tg5abdnqmjh9f6vhk220q.apps.googleusercontent.com',
    iosBundleId: 'com.example.agentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjeQ5mDNzB6GvZlmdM1XWo3Wo1sIE5KGE',
    appId: '1:752415718905:ios:71c7e28df8799251c8d128',
    messagingSenderId: '752415718905',
    projectId: 'agent-app-67bc4',
    storageBucket: 'agent-app-67bc4.firebasestorage.app',
    iosClientId: '752415718905-46n420cu1l4tg5abdnqmjh9f6vhk220q.apps.googleusercontent.com',
    iosBundleId: 'com.example.agentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYSqe4buWmmknIlEDeTpPn_5cTYemdI8E',
    appId: '1:752415718905:web:562e427476739981c8d128',
    messagingSenderId: '752415718905',
    projectId: 'agent-app-67bc4',
    authDomain: 'agent-app-67bc4.firebaseapp.com',
    storageBucket: 'agent-app-67bc4.firebasestorage.app',
  );

}
