import '../../features/properties/models/property_model.dart';

final mockProperties = [
  PropertyModel(
    id: 'prop1',
    title: 'Modern Family House',
    description: 'Luxury modern villa with full amenities, pool and security.',
    state: 'Lagos',
    lga: 'Eti-Osa',
    community: 'Lekki Phase 1',
    address: 'Lekki, Lagos',
    price: 250000000,
    imageUrls: ['https://images.unsplash.com/photo-1568605114967-8130f3a36994'],
    videoUrls: [],
    contactPhone: '08012345678',
    whatsappNumber: '08012345678',
    category: 'house',
    amenities: ['4 Bedrooms', '3 Bathrooms', 'Swimming Pool', 'Security'],
    ownerId: 'landlord1',
    ownerName: 'John Doe',
    isApproved: true,
    approvalStatus: 'approved',
    viewsCount: 128,
    favoritesCount: 34,
    inquiriesCount: 12,
    createdAt: DateTime(2026, 6, 1),
  ),
  PropertyModel(
    id: 'prop2',
    title: 'Luxury Apartment',
    description: 'Stunning premium apartment with panoramic view of the lagoon.',
    state: 'Lagos',
    lga: 'Lagos Island',
    community: 'Victoria Island',
    address: 'Victoria Island, Lagos',
    price: 180000000,
    imageUrls: ['https://images.unsplash.com/photo-1570129477492-45c003edd2be'],
    videoUrls: [],
    contactPhone: '08087654321',
    whatsappNumber: '08087654321',
    category: 'apartment',
    amenities: ['3 Bedrooms', '2 Bathrooms', 'Gym', 'Concierge'],
    ownerId: 'landlord2',
    ownerName: 'Jane Smith',
    isApproved: true,
    approvalStatus: 'approved',
    viewsCount: 95,
    favoritesCount: 21,
    inquiriesCount: 8,
    createdAt: DateTime(2026, 6, 1),
  ),
];
