const List<Map<String, String>> nigerianBanks = [
  {'code': '058', 'name': 'Guaranty Trust Bank (GTBank)'},
  {'code': '044', 'name': 'Access Bank'},
  {'code': '057', 'name': 'Zenith Bank PLC'},
  {'code': '033', 'name': 'United Bank for Africa (UBA)'},
  {'code': '011', 'name': 'First Bank of Nigeria'},
  {'code': '035', 'name': 'Wema Bank PLC'},
  {'code': '214', 'name': 'First City Monument Bank (FCMB)'},
  {'code': '070', 'name': 'Fidelity Bank'},
  {'code': '232', 'name': 'Sterling Bank'},
  {'code': '032', 'name': 'Union Bank of Nigeria'},
  {'code': '221', 'name': 'Stanbic IBTC Bank'},
  {'code': '076', 'name': 'Polaris Bank'},
  {'code': '082', 'name': 'Keystone Bank'},
  {'code': '050', 'name': 'EcoBank'},
  {'code': '068', 'name': 'Standard Chartered Bank'},
  {'code': '101', 'name': 'Providus Bank'},
  {'code': '215', 'name': 'Unity Bank'},
  {'code': '030', 'name': 'Heritage Bank'},
  {'code': '301', 'name': 'Jaiz Bank'},
  {'code': '000027', 'name': 'Globus Bank'},
  {'code': '000025', 'name': 'Titan Trust Bank'},
  {'code': '000026', 'name': 'Taj Bank'},
  {'code': '090110', 'name': 'VFD Microfinance Bank'},
  {'code': '090175', 'name': 'Rubies MFB'},
  {'code': '090267', 'name': 'Kuda Bank'},
  {'code': '090405', 'name': 'Moniepoint Microfinance Bank'},
  {'code': '100004', 'name': 'OPay Digital Services'},
  {'code': '100033', 'name': 'PalmPay'},
  {'code': '090311', 'name': 'Sparkle Microfinance Bank'},
  {'code': '090281', 'name': 'Mint Finex MFB'},
  {'code': '090328', 'name': 'Eyowo'},
  {'code': '090393', 'name': 'Daylight Microfinance Bank'},
  {'code': '090321', 'name': 'Kredi Money Microfinance Bank'},
  {'code': '090115', 'name': 'TCF MFB'},
  {'code': '090401', 'name': 'Dot Microfinance Bank'},
  {'code': '090432', 'name': 'Carbon'},
  {'code': '090558', 'name': 'Shago Payments'},
  {'code': '090177', 'name': 'LAPO Microfinance Bank'},
  {'code': '090270', 'name': 'AB Microfinance Bank'},
  {'code': '090325', 'name': 'Sparkle'},
];
